const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const ts = require('typescript');
const root = path.resolve(__dirname, '../../../..');
const cache = new Map();
function readModule(file) {
  if (cache.has(file)) return cache.get(file);
  const module = { exports: {} }; cache.set(file, module.exports);
  const code = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2017 } }).outputText;
  const localRequire = name => name.startsWith('.') ? readModule(path.resolve(path.dirname(file), name + '.ts')) : require(name);
  vm.runInNewContext(code, { module, exports: module.exports, require: localRequire, Date, Number, Math, Error });
  return module.exports;
}
const engine = readModule(path.join(root, 'components/TemscoV3/valuation.ts'));
const market = readModule(path.join(root, 'components/TemscoV3/marketInputs.ts'));
const evidence = JSON.parse(fs.readFileSync(path.join(root, 'projects/temsco/v3/research/wacc.json')));
const expected = [0.1092941964, 0.1146757681, 0.0873188450, 0.0955752561];
market.waccReferences.forEach((v, i) => assert.ok(Math.abs(v.wacc - expected[i]) < 1e-9));
assert.equal(engine.terminalGrowth, 0);
assert.equal(engine.zeroGrowthTerminal(100, .10), 1000);
const period = { label: '2027', cashDate: '2027-09-08', ebit: 100, cashOperatingTax: 20, depreciation: 10, capex: 15, capitalizedDevelopment: 5, deltaOperatingWorkingCapital: 7 };
assert.equal(engine.calculateFcff(period), 63);
assert.equal(engine.calculateFcff({ ...period, depreciation: null }), null);
const dcf = engine.discountDcf([period], '2026-09-08', .10, '2027-09-08', 80);
assert.ok(Math.abs(dcf.enterpriseValue - (63 + 800) / 1.1) < 1e-9);
assert.equal(engine.discountDcf([{ ...period, capex: null }], '2026-09-08', .10, '2027-09-08', 80).enterpriseValue, null);
assert.throws(() => engine.discountDcf([{ ...period, cashDate: '2027-02-30' }], '2026-09-08', .1, '2027-09-08', 80));
assert.throws(() => engine.calculateWacc({ ...market.marketInputs, betaUnlevered: 1, debtEquity: -.5, debtCost: .05 }));
assert.equal(engine.fundingNeed(10, -25, 5), 20);
assert.equal(engine.fundingNeed(10, 15, 5), 0);
assert.ok(Math.abs(engine.ownershipAfterRound(.2, 80, 20) - .16) < 1e-12);
assert.throws(() => engine.fundingNeed(NaN, -25, 5));
assert.throws(() => engine.ownershipAfterRound(.2, NaN, 20));
const runtimePeriods = JSON.parse(fs.readFileSync(path.join(root, 'components/TemscoV3/companyForecast.json'))).periods;
const sourcePeriods = JSON.parse(fs.readFileSync(path.join(root, 'projects/temsco/v3/research/company-forecast.json'))).periods;
assert.deepEqual(runtimePeriods, sourcePeriods);
const result = { passed: true, marketWacc: market.waccReferences.map(v => ({ industry: v.name, debtProxy: v.rating, wacc: v.wacc })), terminalGrowth: 0, sourcePeriodsMatch: true, checked: ['FCFF signs and missing-data propagation', 'g0 perpetuity and discounted timing', 'calendar-date validation', 'WACC industry metadata compatibility', 'non-finite/negative input rejection', 'financing shortfall', 'round dilution'], currentEnterpriseValue: null, reason: 'valuation-date stub/full D&A/operating tax/maintenance capex/NWC unresolved', referenceSources: evidence.sources.length };
fs.writeFileSync(path.join(__dirname, 'finance-check.json'), JSON.stringify(result, null, 2));
console.log(JSON.stringify(result));
